### ISSUE TITLE
How to setup vertical-align correctly

### ISSUE THREAD

**Issue by Kikobeats** [gorangajic/react-icons#68]
Components uses `middle` by default. How is the approach for use another value? For example, `baseline`.

**Comment by Prinzhorn** [comment]
`style` prop

```js
class Question extends React.Component {
    render() {
        return <h3> Lets go for a <FaBeer style={{verticalAlign: 'baseline'}} />? </h3>
    }
}
```

**Comment by Kikobeats** [comment]
Thanks!

**Comment by kumarharsh** [comment]
Hey, I wanted to suggest that the default verticalAlign be left to `baseline`.

### Usecase
When using with text, it's almost always the case that the icon should align with the baseline instead of the text-middle. And when putting inside buttons as a standalone icon, the button's css would already take case of alignment.
